version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.10.6-management-alpine"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork

  postgres_db:
    container_name: postgres_db
    image: postgres:14.8
    environment:
      - POSTGRES_USER=swed19
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CurrencyStorageDb
    ports:
      - 5442:5432
    networks:
      - mynetwork
    volumes:
      - app_data:/var/lib/postgresql/data

  crawler:
    container_name: crawler_app
    build: 
      context: ./Crawler
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE__ENVIRONMENT=Test
      - Swedlg_CurrencyExchanger_CurrencyNotificationConnectionDbStringPostgres=Host=postgres_db;Port=5432;Database=CurrencyNotificationServiceDb;Username=swed19;Password=postgres
      - RabbitMQ__RabbitUrl=rabbitmq
      - RabbitMQ__RabbitHost=/
      - RabbitMQ__RabbitUser=guest
      - RabbitMQ__RabbitPassword=guest
    ports:
      - 7049:80
    depends_on:
     - postgres_db
     - rabbitmq
    networks:
      - mynetwork

  converter:
    container_name: converter_app
    build: 
      context: ./Converter
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE__ENVIRONMENT=Test
      - Swedlg_CurrencyExchanger_RabbitServer={"RabbitServer":{ "Url":"rabbitmq","Host":"currency-exchanger","User":"currency-exchanger-guest","Password":"currency-exchanger-guest"}}
      - RabbitMQ__RabbitUrl=rabbitmq
      - RabbitMQ__RabbitHost=/
      - RabbitMQ__RabbitUser=guest
      - RabbitMQ__RabbitPassword=guest
    depends_on:
     - rabbitmq
    networks:
      - mynetwork

  storage:
    container_name: storage_app
    build: 
      context: ./Storage
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE__ENVIRONMENT=Test
      - Swedlg_CurrencyExchanger_CurrencyStorageConnectionDbString=Host=postgres_db;Port=5432;Database=CurrencyStorageDb;Username=swed19;Password=postgres
      - RabbitMQ__RabbitUrl=rabbitmq
      - RabbitMQ__RabbitHost=/
      - RabbitMQ__RabbitUser=guest
      - RabbitMQ__RabbitPassword=guest
    ports: 
      - 7036:80
    depends_on:
     - postgres_db
     - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  app_data: